# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.md')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')

setup(
    long_description=readme,
    name='pyroclast',
    version='0.1.0',
    description='Data Platform Integration Library',
    python_requires='==3.*,>=3.7.0',
    project_urls={
        "homepage": "https://github.com/kudu/pyroclast",
        "repository": "https://github.com/kudu/pyroclast"
    },
    author='Eric Lee',
    author_email='elee@kududyn.com',
    classifiers=[
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.7', 'Private :: Do Not Upload'
    ],
    packages=[
        'pyroclast', 'pyroclast.common', 'pyroclast.data', 'pyroclast.sdk'
    ],
    package_dir={"": "."},
    package_data={},
    install_requires=[
        'namesgenerator==0.3', 'python-nomad==1.*,>=1.1.0', 'tenacity==5.*'
    ],
    extras_require={
        "dev": ["pytest", "pytest-black", "pytest-cov", "pytest-flake8"],
        "dgraph": ["pydgraph==2.*,>=2.0.2"],
        "nats": [
            "asyncio-nats-client==0.*,>=0.9.2",
            "asyncio-nats-streaming==0.*,>=0.4.0"
        ],
        "redis": ["redis==3.*,>=3.3.0"],
        "s3": ["boto3==1.*,>=1.10.0"],
        "sonic": ["asonic==1.*,>=1.0.3"]
    },
)
